# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: 'en'
ignorePaths:
  - ./pack-{decoration,ecosystem,platform}-*/
  - ./pnpm-lock.yaml
  - ./extension-list.json
words:
  - hyperupcall
  - edwinkofler
  - kofler
  - Otternaut
  - KHTML
  - Kratz
  - Andersonm
  - Alejo2083
  - Viebrock
  - Yukihiro
  - Matsumoto
  - unrs
